# Default values for dpdkchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: robinsys/dpdk
  tag: v1 
  pullPolicy: IfNotPresent

upf:
  replicas: 1
  annotations:
    robin.io/networks: '[{"ippool": "sriov1"}, {"ippool": "sriov2"}]'
  resources: 
    limits:
      cpu: 6
      memory: 1Gi
      hugepages-1Gi: 3Gi
    requests:
      cpu: 6
      memory: 1Gi
      hugepages-1Gi: 3Gi

ue:
  replicas: 1
  annotations:
    robin.io/networks: '[{"ippool": "sriov1"}, {"ippool": "sriov2"}]'

  resources: 
    limits:
      cpu: 4
      memory: 1Gi
      hugepages-1Gi: 3Gi
    requests:
      cpu: 4
      memory: 1Gi
      hugepages-1Gi: 3Gi

nodeSelector: {}

tolerations: []
## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

affinity: {}
